// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  name: __t.string(),
  isGuest: __t.bool().name("is_guest"),
  zoneId: __t.string().name("zone_id"),
  x: __t.f64(),
  y: __t.f64(),
  dirX: __t.i32().name("dir_x"),
  dirY: __t.i32().name("dir_y"),
  movedAt: __t.timestamp().name("moved_at"),
  online: __t.bool(),
  lastChatAt: __t.option(__t.timestamp()).name("last_chat_at"),
  running: __t.bool(),
  color: __t.i32(),
  carrying: __t.string(),
  path: __t.string(),
  style: __t.i32(),
  equippedMainHand: __t.string().name("equipped_main_hand"),
  equipmentAction: __t.string().name("equipment_action"),
  equipmentActionAt: __t.timestamp().name("equipment_action_at"),
  equippedMainHandInventoryId: __t.u64().name("equipped_main_hand_inventory_id"),
  faceX: __t.i32().name("face_x"),
  faceY: __t.i32().name("face_y"),
  carryingStyle: __t.string().name("carrying_style"),
  health: __t.i32(),
  dead: __t.bool(),
  respawnAt: __t.option(__t.timestamp()).name("respawn_at"),
  equippedOffHand: __t.string().name("equipped_off_hand"),
  equippedOffHandInventoryId: __t.u64().name("equipped_off_hand_inventory_id"),
  lastDamagedAt: __t.timestamp().name("last_damaged_at"),
  cheatSpeed: __t.f64().name("cheat_speed"),
  cheatFly: __t.bool().name("cheat_fly"),
  cheatInvulnerable: __t.bool().name("cheat_invulnerable"),
  cheatNoclip: __t.bool().name("cheat_noclip"),
  z: __t.f64(),
  dirZ: __t.i32().name("dir_z"),
  kindlingCharge: __t.f64().name("kindling_charge"),
  kindlingChargeAt: __t.timestamp().name("kindling_charge_at"),
  provokedAt: __t.timestamp().name("provoked_at"),
});
