// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  slug: __t.string(),
  zoneId: __t.string().name("zone_id"),
  x: __t.i32(),
  y: __t.i32(),
  status: __t.string(),
  fuelSpent: __t.i32().name("fuel_spent"),
  emberHeartSpent: __t.bool().name("ember_heart_spent"),
  ignitionEndsAt: __t.timestamp().name("ignition_ends_at"),
});
