// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Boulder = __t.object("Boulder", {
  id: __t.u64(),
  zoneId: __t.string(),
  x: __t.i32(),
  y: __t.i32(),
});
export type Boulder = __Infer<typeof Boulder>;

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.u64(),
  zoneId: __t.string(),
  sender: __t.identity(),
  name: __t.string(),
  text: __t.string(),
  createdAt: __t.timestamp(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const ClaimCode = __t.object("ClaimCode", {
  code: __t.string(),
  guest: __t.identity(),
  createdAt: __t.timestamp(),
});
export type ClaimCode = __Infer<typeof ClaimCode>;

export const Hog = __t.object("Hog", {
  id: __t.u64(),
  zoneId: __t.string(),
  x: __t.i32(),
  y: __t.i32(),
  dirX: __t.i32(),
  dirY: __t.i32(),
  movedAt: __t.timestamp(),
  path: __t.string(),
  homeX: __t.i32(),
  homeY: __t.i32(),
});
export type Hog = __Infer<typeof Hog>;

export const HogWander = __t.object("HogWander", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type HogWander = __Infer<typeof HogWander>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  isGuest: __t.bool(),
  zoneId: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
  dirX: __t.i32(),
  dirY: __t.i32(),
  movedAt: __t.timestamp(),
  online: __t.bool(),
  lastChatAt: __t.option(__t.timestamp()),
  running: __t.bool(),
  color: __t.i32(),
  carrying: __t.string(),
  path: __t.string(),
  style: __t.i32(),
});
export type Player = __Infer<typeof Player>;

