// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Boulder = __t.object("Boulder", {
  id: __t.u64(),
  zoneId: __t.string(),
  x: __t.i32(),
  y: __t.i32(),
  health: __t.i32(),
  cellId: __t.u32(),
});
export type Boulder = __Infer<typeof Boulder>;

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.u64(),
  zoneId: __t.string(),
  sender: __t.identity(),
  name: __t.string(),
  text: __t.string(),
  createdAt: __t.timestamp(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const ClaimCode = __t.object("ClaimCode", {
  code: __t.string(),
  guest: __t.identity(),
  createdAt: __t.timestamp(),
});
export type ClaimCode = __Infer<typeof ClaimCode>;

export const CreatureRegen = __t.object("CreatureRegen", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type CreatureRegen = __Infer<typeof CreatureRegen>;

export const GhostHaunt = __t.object("GhostHaunt", {
  id: __t.u64(),
  zoneId: __t.string(),
  x: __t.i32(),
  y: __t.i32(),
  createdAt: __t.timestamp(),
});
export type GhostHaunt = __Infer<typeof GhostHaunt>;

export const GroundItem = __t.object("GroundItem", {
  id: __t.u64(),
  zoneId: __t.string(),
  item: __t.string(),
  x: __t.i32(),
  y: __t.i32(),
  qty: __t.i32(),
});
export type GroundItem = __Infer<typeof GroundItem>;

export const Inventory = __t.object("Inventory", {
  id: __t.u64(),
  playerId: __t.identity(),
  item: __t.string(),
  qty: __t.i32(),
});
export type Inventory = __Infer<typeof Inventory>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  isGuest: __t.bool(),
  zoneId: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
  dirX: __t.i32(),
  dirY: __t.i32(),
  movedAt: __t.timestamp(),
  online: __t.bool(),
  lastChatAt: __t.option(__t.timestamp()),
  running: __t.bool(),
  color: __t.i32(),
  carrying: __t.string(),
  path: __t.string(),
  style: __t.i32(),
  equippedMainHand: __t.string(),
  equipmentAction: __t.string(),
  equipmentActionAt: __t.timestamp(),
  equippedMainHandInventoryId: __t.u64(),
  faceX: __t.i32(),
  faceY: __t.i32(),
  carryingStyle: __t.string(),
  health: __t.i32(),
  dead: __t.bool(),
  respawnAt: __t.option(__t.timestamp()),
  equippedOffHand: __t.string(),
  equippedOffHandInventoryId: __t.u64(),
  lastDamagedAt: __t.timestamp(),
  cheatSpeed: __t.f64(),
  cheatFly: __t.bool(),
  cheatInvulnerable: __t.bool(),
  cheatNoclip: __t.bool(),
  z: __t.f64(),
  dirZ: __t.i32(),
});
export type Player = __Infer<typeof Player>;

export const PlayerConnection = __t.object("PlayerConnection", {
  connectionId: __t.string(),
  playerId: __t.identity(),
  connectedAt: __t.timestamp(),
});
export type PlayerConnection = __Infer<typeof PlayerConnection>;

export const PlayerRespawn = __t.object("PlayerRespawn", {
  scheduledId: __t.u64(),
  playerId: __t.identity(),
  scheduledAt: __t.scheduleAt(),
});
export type PlayerRespawn = __Infer<typeof PlayerRespawn>;

export const Tree = __t.object("Tree", {
  id: __t.u64(),
  zoneId: __t.string(),
  x: __t.i32(),
  y: __t.i32(),
  health: __t.i32(),
});
export type Tree = __Infer<typeof Tree>;

export const WorldState = __t.object("WorldState", {
  id: __t.u32(),
  skyLocked: __t.bool(),
  skyPhase: __t.f64(),
});
export type WorldState = __Infer<typeof WorldState>;

