// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  name: __t.string(),
  isGuest: __t.bool().name("is_guest"),
  zoneId: __t.string().name("zone_id"),
  x: __t.f64(),
  y: __t.f64(),
  dirX: __t.i32().name("dir_x"),
  dirY: __t.i32().name("dir_y"),
  movedAt: __t.timestamp().name("moved_at"),
  online: __t.bool(),
  lastChatAt: __t.option(__t.timestamp()).name("last_chat_at"),
  running: __t.bool(),
  color: __t.i32(),
  carrying: __t.string(),
  path: __t.string(),
});
