// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.u64(),
  zoneId: __t.string(),
  sender: __t.identity(),
  name: __t.string(),
  text: __t.string(),
  createdAt: __t.timestamp(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  isGuest: __t.bool(),
  zoneId: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
  dirX: __t.i32(),
  dirY: __t.i32(),
  movedAt: __t.timestamp(),
  online: __t.bool(),
  lastChatAt: __t.option(__t.timestamp()),
});
export type Player = __Infer<typeof Player>;

