// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ChatReducer from "../chat_reducer";
import DiscardItemReducer from "../discard_item_reducer";
import DropItemReducer from "../drop_item_reducer";
import EmergeReducer from "../emerge_reducer";
import EnterCaveReducer from "../enter_cave_reducer";
import EquipItemReducer from "../equip_item_reducer";
import FaceReducer from "../face_reducer";
import HauntGhostReducer from "../haunt_ghost_reducer";
import HealSelfReducer from "../heal_self_reducer";
import InteractReducer from "../interact_reducer";
import MoveReducer from "../move_reducer";
import MoveToReducer from "../move_to_reducer";
import RecolorReducer from "../recolor_reducer";
import RedeemClaimReducer from "../redeem_claim_reducer";
import RenameReducer from "../rename_reducer";
import RescueReducer from "../rescue_reducer";
import ResetBouldersReducer from "../reset_boulders_reducer";
import ResetDarkCreaturesReducer from "../reset_dark_creatures_reducer";
import RestyleReducer from "../restyle_reducer";
import SetCheatsReducer from "../set_cheats_reducer";
import SetLiftReducer from "../set_lift_reducer";
import SetSkyReducer from "../set_sky_reducer";
import SpawnReducer from "../spawn_reducer";
import StartClaimReducer from "../start_claim_reducer";
import UseEquippedReducer from "../use_equipped_reducer";

export type ChatParams = __Infer<typeof ChatReducer>;
export type DiscardItemParams = __Infer<typeof DiscardItemReducer>;
export type DropItemParams = __Infer<typeof DropItemReducer>;
export type EmergeParams = __Infer<typeof EmergeReducer>;
export type EnterCaveParams = __Infer<typeof EnterCaveReducer>;
export type EquipItemParams = __Infer<typeof EquipItemReducer>;
export type FaceParams = __Infer<typeof FaceReducer>;
export type HauntGhostParams = __Infer<typeof HauntGhostReducer>;
export type HealSelfParams = __Infer<typeof HealSelfReducer>;
export type InteractParams = __Infer<typeof InteractReducer>;
export type MoveParams = __Infer<typeof MoveReducer>;
export type MoveToParams = __Infer<typeof MoveToReducer>;
export type RecolorParams = __Infer<typeof RecolorReducer>;
export type RedeemClaimParams = __Infer<typeof RedeemClaimReducer>;
export type RenameParams = __Infer<typeof RenameReducer>;
export type RescueParams = __Infer<typeof RescueReducer>;
export type ResetBouldersParams = __Infer<typeof ResetBouldersReducer>;
export type ResetDarkCreaturesParams = __Infer<typeof ResetDarkCreaturesReducer>;
export type RestyleParams = __Infer<typeof RestyleReducer>;
export type SetCheatsParams = __Infer<typeof SetCheatsReducer>;
export type SetLiftParams = __Infer<typeof SetLiftReducer>;
export type SetSkyParams = __Infer<typeof SetSkyReducer>;
export type SpawnParams = __Infer<typeof SpawnReducer>;
export type StartClaimParams = __Infer<typeof StartClaimReducer>;
export type UseEquippedParams = __Infer<typeof UseEquippedReducer>;

