// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ChatReducer from "../chat_reducer";
import DiscardItemReducer from "../discard_item_reducer";
import DropItemReducer from "../drop_item_reducer";
import EquipItemReducer from "../equip_item_reducer";
import FaceReducer from "../face_reducer";
import HauntGhostReducer from "../haunt_ghost_reducer";
import InteractReducer from "../interact_reducer";
import MoveReducer from "../move_reducer";
import MoveToReducer from "../move_to_reducer";
import PushReducer from "../push_reducer";
import RecolorReducer from "../recolor_reducer";
import RedeemClaimReducer from "../redeem_claim_reducer";
import RenameReducer from "../rename_reducer";
import ResetBouldersReducer from "../reset_boulders_reducer";
import ResetHogsReducer from "../reset_hogs_reducer";
import RestyleReducer from "../restyle_reducer";
import SpawnReducer from "../spawn_reducer";
import StartClaimReducer from "../start_claim_reducer";
import UseEquippedReducer from "../use_equipped_reducer";

export type ChatParams = __Infer<typeof ChatReducer>;
export type DiscardItemParams = __Infer<typeof DiscardItemReducer>;
export type DropItemParams = __Infer<typeof DropItemReducer>;
export type EquipItemParams = __Infer<typeof EquipItemReducer>;
export type FaceParams = __Infer<typeof FaceReducer>;
export type HauntGhostParams = __Infer<typeof HauntGhostReducer>;
export type InteractParams = __Infer<typeof InteractReducer>;
export type MoveParams = __Infer<typeof MoveReducer>;
export type MoveToParams = __Infer<typeof MoveToReducer>;
export type PushParams = __Infer<typeof PushReducer>;
export type RecolorParams = __Infer<typeof RecolorReducer>;
export type RedeemClaimParams = __Infer<typeof RedeemClaimReducer>;
export type RenameParams = __Infer<typeof RenameReducer>;
export type ResetBouldersParams = __Infer<typeof ResetBouldersReducer>;
export type ResetHogsParams = __Infer<typeof ResetHogsReducer>;
export type RestyleParams = __Infer<typeof RestyleReducer>;
export type SpawnParams = __Infer<typeof SpawnReducer>;
export type StartClaimParams = __Infer<typeof StartClaimReducer>;
export type UseEquippedParams = __Infer<typeof UseEquippedReducer>;

