// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ChatReducer from "../chat_reducer";
import MoveReducer from "../move_reducer";
import PushReducer from "../push_reducer";
import RedeemClaimReducer from "../redeem_claim_reducer";
import RenameReducer from "../rename_reducer";
import SpawnReducer from "../spawn_reducer";
import StartClaimReducer from "../start_claim_reducer";

export type ChatParams = __Infer<typeof ChatReducer>;
export type MoveParams = __Infer<typeof MoveReducer>;
export type PushParams = __Infer<typeof PushReducer>;
export type RedeemClaimParams = __Infer<typeof RedeemClaimReducer>;
export type RenameParams = __Infer<typeof RenameReducer>;
export type SpawnParams = __Infer<typeof SpawnReducer>;
export type StartClaimParams = __Infer<typeof StartClaimReducer>;

