// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ChatReducer from "../chat_reducer";
import MoveReducer from "../move_reducer";

export type ChatParams = __Infer<typeof ChatReducer>;
export type MoveParams = __Infer<typeof MoveReducer>;

