/**
 * Generates the indexed avatar art in `shared/sprite_art.ts`.
 *
 * The committed `sprite_art.ts` is indexed pixel maps the runtime and tests
 * consume, but those maps are tedious to author by hand. This tool combines the
 * per-creature paint logic in `tools/art/` (one file per creature — `trogg.ts`,
 * `hog.ts`, `buff.ts`, `dino.ts`, `chicken.ts`, `ghost.ts`, over the shared
 * `rig.ts`), paints each 32x48 frame, and quantises it into a per-frame palette
 * + key map.
 *
 * Art direction is Pokémon Gold/Silver: a tight flat palette and chunky flat
 * shapes, with a single dilation pass tracing a clean dark outline around the
 * whole silhouette (`outlinePass`), composited over a soft ground shadow. To
 * edit a creature, open its file in `tools/art/`; this combiner only wires them
 * together and emits.
 *
 * Pipeline: `pnpm sprite-art` (this tool) → `shared/sprite_art.ts` → the
 * renderer in `sprites.ts` → `pnpm sprites` → the committed PNG/atlas.
 *
 * Standalone Node (tsx) — not part of the client or the module bundle.
 */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { FRAME_H, FRAME_W, frames, rgbaSink, type Facing, type FrameName, type Kind, type PixelSink } from "../shared/sprites.ts";
import { compositeOver, disc, fmtArt, outlinePass, PIXEL_KEYS, quantize } from "./pixel_paint.ts";
import type { View } from "./art/rig.ts";
import { TROGG_SKINS, troggDraw } from "./art/trogg.ts";
import { HOG_SKINS, hogDraw } from "./art/hog.ts";
import { BUFF, buffDraw } from "./art/buff.ts";
import { DINO, dinoDraw } from "./art/dino.ts";
import { CHICK, chickenDraw } from "./art/chicken.ts";
import { GHOST, ghostDrawArt } from "./art/ghost.ts";

// ── frame painting: dispatch, layer, outline, composite ─────────────────────────

function outlineColour(kind: Kind, style: string): number {
  if (kind === "trogg") return (TROGG_SKINS[style] ?? TROGG_SKINS.moss!).out;
  if (style === "buff") return BUFF.out;
  if (style === "dino") return DINO.out;
  if (style === "chicken") return CHICK.out;
  return (HOG_SKINS[style] ?? HOG_SKINS.classic!).out;
}

function drawCharacter(p: PixelSink, kind: Kind, style: string, view: View, frame: FrameName): void {
  if (kind === "trogg") troggDraw(p, view, frame, TROGG_SKINS[style] ?? TROGG_SKINS.moss!);
  else if (style === "buff") buffDraw(p, view, frame);
  else if (style === "dino") dinoDraw(p, view, frame);
  else if (style === "chicken") chickenDraw(p, view, frame);
  else hogDraw(p, view, frame, HOG_SKINS[style] ?? HOG_SKINS.classic!);
}

function paintFrame(kind: Kind, style: string, facing: Facing, frame: FrameName): Uint8Array {
  // character on its own layer (outlined), composited over a soft ground shadow
  const layer = new Uint8Array(FRAME_W * FRAME_H * 4);
  const cs = rgbaSink(layer, FRAME_W, FRAME_H);
  const flip = facing === "left";
  const p: PixelSink = { set: (x, y, c) => cs.set(flip ? FRAME_W - 1 - x : x, y, c) };
  const view: View = facing === "left" || facing === "right" ? "side" : facing;
  drawCharacter(p, kind, style, view, frame);
  outlinePass(layer, outlineColour(kind, style), FRAME_W, FRAME_H);

  const data = new Uint8Array(FRAME_W * FRAME_H * 4);
  disc(rgbaSinkAlpha(data, 70), 15.5, 43, 11, 3.2, 0x000000);
  compositeOver(data, layer);
  return data;
}

/** A sink that paints at a fixed alpha — used only for the ground shadow. */
function rgbaSinkAlpha(data: Uint8Array, alpha: number): PixelSink {
  const base = rgbaSink(data, FRAME_W, FRAME_H);
  return { set: (x, y, c) => base.set(x, y, c, alpha) };
}

function paintGhost(): Uint8Array {
  const layer = new Uint8Array(FRAME_W * FRAME_H * 4);
  ghostDrawArt(rgbaSink(layer, FRAME_W, FRAME_H));
  outlinePass(layer, GHOST.out, FRAME_W, FRAME_H);
  const data = new Uint8Array(FRAME_W * FRAME_H * 4);
  disc(rgbaSinkAlpha(data, 70), 15.5, 43, 12, 3.4, 0x000000);
  compositeOver(data, layer);
  return data;
}

// ── emit ────────────────────────────────────────────────────────────────────────

const header = `/**
 * Indexed source art for the avatar sprite sheet.
 *
 * Each frame is a 32x48 text pixel map. \`.\` is transparent; any other
 * character indexes into that frame's local RGBA palette using PIXEL_KEYS.
 * The sprite renderer in \`sprites.ts\` blits these maps into the shared sheet
 * and the runtime canvas texture.
 *
 * GENERATED by \`tools/gen-sprite-art.ts\` (\`pnpm sprite-art\`). The paint logic
 * lives in \`tools/art/\` (one file per creature) — edit it and regenerate, don't
 * hand-edit this file.
 */

export interface IndexedSpriteArt {
  palette: readonly number[];
  pixels: readonly string[];
}

export const PIXEL_KEYS = ${JSON.stringify(PIXEL_KEYS)};

`;

const entries = frames().map((f) => {
  const art = quantize(paintFrame(f.kind, f.style, f.facing, f.frame), FRAME_W, FRAME_H);
  return `  ${JSON.stringify(f.name)}: ${fmtArt(art, "  ")},`;
});

const ghost = fmtArt(quantize(paintGhost(), FRAME_W, FRAME_H), "");

const out =
  header +
  `export const AVATAR_FRAME_ART: Record<string, IndexedSpriteArt> = {\n${entries.join("\n")}\n};\n\n` +
  `export const GHOST_ART: IndexedSpriteArt = ${ghost};\n`;

const OUT_PATH = join(dirname(fileURLToPath(import.meta.url)), "..", "shared", "sprite_art.ts");
writeFileSync(OUT_PATH, out);
console.log(`Wrote ${entries.length} frames + ghost → ${OUT_PATH}`);
