/**
 * Generates the indexed world-prop art in `shared/item_art.ts` — the held/ground
 * tools (pickaxe, shovel, sword), the stone resource, and the boulder.
 *
 * Same Pokémon Gold/Silver pipeline and helpers as the avatar art: flat shapes
 * in a tight palette, painted upright on their own layer, then a single dilation
 * pass traces a crisp dark outline around the silhouette. Items carry no baked
 * shadow — the world renderer drops its own contact shadow under a ground item.
 *
 * Pipeline: `pnpm item-art` (this tool) → `shared/item_art.ts` → the renderer in
 * `sprites.ts` (`blitArt`) → `src/game/items.ts` texture. Edit the draw code
 * here, never the generated maps.
 *
 * Standalone Node (tsx) — not part of the client or the module bundle.
 */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { rgbaSink, type PixelSink } from "../shared/sprites.ts";
import { disc, dot, fmtArt, line, outlinePass, quantize, rect, shaded } from "./pixel_paint.ts";

/** Every prop is painted on this square so they share one atlas cell size. */
const W = 24;
const H = 24;

const WOOD = 0x6b3f24;
const WOOD_DK = 0x46280f;
const STEEL = 0xccd6dc;
const STEEL_DK = 0x8b969c;
const GOLD = 0xe6b53f;
const GOLD_DK = 0xb6862a;
const BRASS = 0xc6a05a;
const BRASS_DK = 0x8f6f38;
const ROCK = 0x8a7257;
const ROCK_LT = 0xa88c6c;
const ROCK_DK = 0x5b4733;
const OUT_TOOL = 0x1a1714;
const OUT_ROCK = 0x241c12;

/** Drawn upright; the world rotates the sprite per facing / for the ground pose. */
function drawSword(p: PixelSink): void {
  // blade, tip up, with a fuller down the middle
  rect(p, 11, 4, 2, 10, STEEL);
  dot(p, 11, 3, STEEL); dot(p, 12, 3, STEEL); dot(p, 11, 2, STEEL);
  for (let y = 4; y <= 13; y++) dot(p, 12, y, STEEL_DK);
  // golden crossguard
  rect(p, 7, 14, 10, 2, GOLD);
  rect(p, 7, 15, 10, 1, GOLD_DK);
  // grip + pommel
  rect(p, 11, 16, 2, 5, WOOD);
  for (let y = 16; y <= 20; y++) dot(p, 12, y, WOOD_DK);
  disc(p, 11.5, 21.5, 1.5, 1.5, GOLD);
}

function drawPickaxe(p: PixelSink): void {
  // handle
  rect(p, 11, 6, 2, 15, WOOD);
  for (let y = 6; y <= 20; y++) dot(p, 12, y, WOOD_DK);
  // double-pick head, curving down at the tips
  rect(p, 10, 4, 4, 3, STEEL_DK);
  line(p, 10, 5, 4, 8, STEEL); line(p, 10, 6, 4, 9, STEEL_DK); dot(p, 3, 8, STEEL);
  line(p, 13, 5, 19, 8, STEEL); line(p, 13, 6, 19, 9, STEEL_DK); dot(p, 20, 8, STEEL);
  rect(p, 10, 4, 4, 1, STEEL);
}

function drawShovel(p: PixelSink): void {
  // spade blade at the top
  rect(p, 8, 4, 8, 4, BRASS);
  disc(p, 11.5, 8.5, 4, 3.2, BRASS);
  for (let y = 4; y <= 10; y++) { dot(p, 14, y, BRASS_DK); dot(p, 15, y, BRASS_DK); }
  dot(p, 11.5, 11.5, BRASS_DK);
  // socket + handle
  rect(p, 11, 9, 2, 11, WOOD);
  for (let y = 9; y <= 19; y++) dot(p, 12, y, WOOD_DK);
  rect(p, 9, 19, 6, 2, WOOD); // grip bar
}

function drawStone(p: PixelSink): void {
  // a small chunky chip of cave rock
  shaded(p, 11.5, 15, 5, 3.6, ROCK, ROCK_DK);
  disc(p, 10, 13.5, 2.2, 1.5, ROCK_LT);
  line(p, 13, 13, 14, 16, ROCK_DK);
}

function drawBoulder(p: PixelSink): void {
  // a big rounded rock nearly filling the cell, lit from the top-left
  shaded(p, 12, 13, 9.6, 9, ROCK, ROCK_DK);
  disc(p, 8, 9, 3.6, 2.8, ROCK_LT);
  line(p, 14, 7, 16, 17, ROCK_DK);
  line(p, 15, 12, 19, 14, ROCK_DK);
  dot(p, 7, 17, ROCK_LT); dot(p, 17, 19, ROCK_LT);
}

interface ItemSpec {
  draw: (p: PixelSink) => void;
  outline: number;
}

/** Insertion order is the atlas column order; `src/game/items.ts` carves frames by name. */
const ITEMS: Record<string, ItemSpec> = {
  pickaxe: { draw: drawPickaxe, outline: OUT_TOOL },
  shovel: { draw: drawShovel, outline: OUT_TOOL },
  sword: { draw: drawSword, outline: OUT_TOOL },
  stone: { draw: drawStone, outline: OUT_ROCK },
  boulder: { draw: drawBoulder, outline: OUT_ROCK },
};

function paintItem(spec: ItemSpec): Uint8Array {
  const layer = new Uint8Array(W * H * 4);
  spec.draw(rgbaSink(layer, W, H));
  outlinePass(layer, spec.outline, W, H);
  return layer;
}

const header = `/**
 * Indexed source art for world props (tools, stone, boulder).
 *
 * Each entry is a ${W}x${H} text pixel map in the same format as \`sprite_art.ts\`;
 * \`.\` is transparent and any other character indexes the entry's local RGBA
 * palette via PIXEL_KEYS. Rendered through \`blitArt\` in \`sprites.ts\`.
 *
 * GENERATED by \`tools/gen-item-art.ts\` (\`pnpm item-art\`). The paint logic there
 * is the source of truth — edit it and regenerate, don't hand-edit this file.
 */

import type { IndexedSpriteArt } from "./sprite_art";

export const ITEM_ART_W = ${W};
export const ITEM_ART_H = ${H};

`;

const entries = Object.entries(ITEMS).map(
  ([name, spec]) => `  ${JSON.stringify(name)}: ${fmtArt(quantize(paintItem(spec), W, H), "  ")},`,
);

const out = header + `export const ITEM_ART: Record<string, IndexedSpriteArt> = {\n${entries.join("\n")}\n};\n`;

const OUT_PATH = join(dirname(fileURLToPath(import.meta.url)), "..", "shared", "item_art.ts");
writeFileSync(OUT_PATH, out);
console.log(`Wrote ${entries.length} item maps → ${OUT_PATH}`);
